### ISSUE TITLE
ERROR: java.lang.Exception: Validation failed. Please contact support for further assistance

### ISSUE THREAD

**Issue by sdm2d11** [SPYDERISK/system-modeller#29]
User Stefano
Instance: https://security.it-innovation.soton.ac.uk/ 
model name: FactoryOfTheFuture

Around 1700 on Friday 02nd June 2023 is when I got the errors (tried a few times).
[Model6479fd1e11752e4e2a3194d0_2023-06-02_16 33 57.nq.gz](https://github.com/SPYDERISK/system-modeller/files/11651554/Model6479fd1e11752e4e2a3194d0_2023-06-02_16.33.57.nq.gz)

**Comment by kenmeacham** [comment]
Just to note also that Stefano was attempting to validate a freshly built model using the domain model: Network Version: 6a3-1-1

**Comment by kenmeacham** [comment]
I extracted the logs from the server. See attached.

[ssm.log.gz](https://github.com/SPYDERISK/system-modeller/files/11651618/ssm.log.gz)

**Comment by kenmeacham** [comment]
I have also replicated the bug using the latest Spyderisk dev branch. The relevent snippet of logs is:

10:10:17.449 ERROR u.a.s.i.s.s.r.ModelController:662: Validation failed:

java.lang.NullPointerException: null
        at uk.ac.soton.itinnovation.security.modelvalidator.Validator.calculateRelationCardinalityConstraint(Validator.java:2260)
        at uk.ac.soton.itinnovation.security.modelvalidator.Validator.calculateAssertedCardinalityConstraints(Validator.java:1846)
        at uk.ac.soton.itinnovation.security.modelvalidator.Validator.validate(Validator.java:157)
        at uk.ac.soton.itinnovation.security.modelvalidator.DesigntimeValidator.validateDesigntimeModel(DesigntimeValidator.java:100)
        at uk.ac.soton.itinnovation.security.modelvalidator.ModelValidator.validateDesigntimeModel(ModelValidator.java:80)
        at uk.ac.soton.itinnovation.security.systemmodeller.rest.ModelController.lambda$validateModel$1(ModelController.java:658)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kenmeacham** [comment]
Assigning to @mike1813 to have a look at the model

**Comment by kenmeacham** [comment]
Just to confirm, the model was created from scratch, but Stefano used the cut & paste features several times, so this might point to a problem in this. Maybe cardinality constraints were not copied??

**Comment by mike1813** [comment]
The model contains some 'garbage' indicating it wasn't created from scratch. I am not familiar with the 'cut and paste' feature, but if it works by copying asserted assets and relationships from some other model, then it will probably allow legacy issues to enter from the other model.

The exception is caused by the asset having no valid population level. This often arises when using an old model from before we introduced support for asset populations - the asserted graph contains assets with no population. The code checks for this and if there is no population, the default level is inserted that would have been used had the user just created the asset manually.

What is happening here is bizarre. there is a population URI, but it is set to 'file:///'. I can only assume this was inserted by the cut and paste feature, possibly because it was asked to copy an asset with no population level.

**Comment by mike1813** [comment]
@sdm2d11 : You should be able to work around this specific problem by manually editing your system model. You should:

- export the model from your system-modeller instance, specifying that you only want to export the asserted graph, and save it on your client system
- delete the model from the system-modeller instance
- gunzip the downloaded model to extract the NQ file
- search for occurrences of the string 'file:///', and delete any line (i.e., the entire Quad) in which this string appears
- gzip the edited NQ file and reimport it into your system-modeller instance.

I just tried this and it worked. For the model you attached at the start of this issue, the 'cleaned' version is attached here.

[FactoryOfTheFuture Issue 29 2023-06-02_16.33.57 - Cleaned.nq.gz](https://github.com/SPYDERISK/system-modeller/files/11652385/FactoryOfTheFuture.Issue.29.2023-06-02_16.33.57.-.Cleaned.nq.gz)

**Comment by sdm2d11** [comment]
To be clear.
The model was done completely from scratch.
The copy/paste feature that I used was inside the model. For instance to create a new process, I did ctrlC-ctrlV of an existing one rather than dragging one from the palette.

I did not import nor copied anything from outside.

As per the cardinality, I found strange that the cardinality of the relationship "ACME Sensors --> MOM Application" was 0-0 and I tried to change it, but the interface did not allow me to. I did not do anything else re: cardinality.

**Comment by mike1813** [comment]
@kenmeacham : how should we proceed? I could insert more defensive code into the validator, but I believe this issue is caused by a bug in the cut-and-paste feature. I am passing this issue back to you, so you can check if that is the cause.

**Comment by mike1813** [comment]
@kenmeacham : I added some more defensive coding that should help avoid crashes caused by these issues. This is now committed to GitHub on branch 29-xxx, which I created from this issue.

**Comment by mike1813** [comment]
The defensive code I added means it is less likely to crash if populations aren't handled by the cut and paste feature. However, this is done by adding a 'singleton' population assertion if the querier can't find anything else that makes sense. That means if the cut and paste feature somehow 'loses' the population level of an asset, the system-modeller won't complain, so users won't notice the original level has been changed.

**Comment by kenmeacham** [comment]
FYI, I can replicate the underlying bug, which I will move to a new issue, but useful to report here too. 

1) Create empty model
2) Create new asset (drag from palette)
3) Validate (works OK)
4) Select the asset
5) Copy and paste the asset (Ctrl-c, Ctrl-v)
5) Validate (fails this time)

You will also see, if you select the copied asset, that it has no population level (see "Asset Details and Population" panel)

**Comment by kenmeacham** [comment]
@mike1813 - I created a new issue (#30) for me to fix the underlying copy and paste bug

I've had a go with the branch; the system model now validates without throwing an exception. The copied asset is then provided with a default population level. Of course this should be the same level as the original asset, but this will be fixed via #30 

Ideally this issue should now have a pull request, so we can more easily look at the code changes and make comments on them if necessary. Could you do that?

**Comment by mike1813** [comment]
Created the pull request that will close this issue. Note that the change just prevents the code from crashing by inserting some default values. This provides a temporary solution pending a fix for the root cause, which is covered by issue #30.

In my view, the temporary fix could be retained once #30 is addressed. Even though the underlying cause can't then be created, someone may still import an old system model NQ file in which the problem was persisted. The temporary fix means that won't crash system-modeller, but users will need to check and possibly reset the population level for assets created using a still buggy cut-and-paste function.
